Drop support for Mongoid 3 and 4 + fix after_fork callback
collectiveidea/delayed_job_mongoid pull request #81
Opened 2021-04-01 18:50 UTC by johnnyshields

- Drop support for Mongoid 3 and 4
- Perform disconnect on after_fork on all Mongoid versions

2021-04-01 19:55 UTC, dblock requested changes
Can we remove mongoid_compatibility from .gemspec or is it used elsewhere?

2021-04-01 19:55 UTC, dblock commented on CHANGELOG.md
> +### 3.0.0 (2019/02/26)
This should be (Next)

2021-04-01 19:55 UTC, dblock commented on README.md
> +(For Mongoid 3 and 4, use 2.x version of this gem)
Add a period.

2021-04-02 07:36 UTC, johnnyshields commented
> Can we remove mongoid_compatibility from .gemspec or is it used elsewhere?

I have removed it, it's not needed anymore.

2021-04-02 07:37 UTC, johnnyshields commented
Please merge and cut a release

2021-04-02 15:10 UTC, merged

2021-04-02 15:12 UTC, dblock commented
Merged. It's nice to see you here @johnnyshields! I added you to the repo maintainers and to rubygems so you can cut the release. Thanks for your help!

2021-04-02 17:57 UTC, johnnyshields commented
Awesome, thanks 👍